### ISSUE TITLE
Blank page happens after pressing default storage

### ISSUE THREAD

**Issue by nolim1t** [blockstack/blockstack-browser#1021]
I've done a fresh install (removed .blockstack directory)

## Operating System

macOS 10.12 (Sierra)

## Browser

Chrome 61.0.3163.100 (Official Build)

## Issue

![blank page after detault storage](https://user-images.githubusercontent.com/83470/32324180-67d7fbe0-bfc2-11e7-9119-8c125cf18686.png)

## Javascript console

```text
2017-11-02T11:39:35.150-0000 INFO utils/logging-utils.js: Logging system enabled
main.js:209029 2017-11-02T11:39:35.155-0000 INFO utils/logging-utils.js: Log server: http://localhost:8333/
main.js:209029 2017-11-02T11:39:35.157-0000 TRACE index.js: NODE_ENV is not production
main.js:209029 2017-11-02T11:39:35.159-0000 DEBUG index.js: Enabling React devtools
main.js:209029 2017-11-02T11:39:35.183-0000 DEBUG App.js: EXISTING_VERSION: 12; CURRENT_VERSION:
      12
main.js:209029 2017-11-02T11:39:35.186-0000 TRACE App.js: componentWillMount
main.js:209029 2017-11-02T11:39:35.206-0000 DEBUG storage/StorageProvidersPage.js: componentDidMount: trying to connect gaia hub...
main.js:209029 2017-11-02T11:39:35.219-0000 ERROR window.addWindowListener('error'): { isTrusted: [Getter] }
main.js:209029 2017-11-02T11:39:35.224-0000 ERROR window.onerror: Uncaught TypeError: Cannot read property 'key' of undefined [TypeError: Cannot read property 'key' of undefined]
TypeError: Cannot read property 'key' of undefined
    at StorageProvidersPage.connectSharedService (http://localhost:8888/js/main.js:2024:51)
    at StorageProvidersPage.componentWillMount (http://localhost:8888/js/main.js:1985:14)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8888/js/main.js:163393:14)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8888/js/main.js:163300:21)
    at Object.mountComponent (http://localhost:8888/js/main.js:169517:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8888/js/main.js:163413:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8888/js/main.js:163300:21)
    at Object.mountComponent (http://localhost:8888/js/main.js:169517:35)
    at ReactDOMComponent.mountChildren (http://localhost:8888/js/main.js:168921:44)
    at ReactDOMComponent._createInitialChildren (http://localhost:8888/js/main.js:164753:32)
main.js:2024 Uncaught TypeError: Cannot read property 'key' of undefined
    at StorageProvidersPage.connectSharedService (main.js:2024)
    at StorageProvidersPage.componentWillMount (main.js:1985)
    at ReactCompositeComponentWrapper.performInitialMount (main.js:163393)
    at ReactCompositeComponentWrapper.mountComponent (main.js:163300)
    at Object.mountComponent (main.js:169517)
    at ReactCompositeComponentWrapper.performInitialMount (main.js:163413)
    at ReactCompositeComponentWrapper.mountComponent (main.js:163300)
    at Object.mountComponent (main.js:169517)
    at ReactDOMComponent.mountChildren (main.js:168921)
    at ReactDOMComponent._createInitialChildren (main.js:164753)
connectSharedService @ main.js:2024
componentWillMount @ main.js:1985
performInitialMount @ main.js:163393
mountComponent @ main.js:163300
mountComponent @ main.js:169517
performInitialMount @ main.js:163413
mountComponent @ main.js:163300
mountComponent @ main.js:169517
mountChildren @ main.js:168921
_createInitialChildren @ main.js:164753
mountComponent @ main.js:164572
mountComponent @ main.js:169517
mountChildren @ main.js:168921
_createInitialChildren @ main.js:164753
mountComponent @ main.js:164572
mountComponent @ main.js:169517
mountChildren @ main.js:168921
_createInitialChildren @ main.js:164753
mountComponent @ main.js:164572
mountComponent @ main.js:169517
mountChildren @ main.js:168921
_createInitialChildren @ main.js:164753
mountComponent @ main.js:164572
mountComponent @ main.js:169517
performInitialMount @ main.js:163413
mountComponent @ main.js:163300
mountComponent @ main.js:169517
performInitialMount @ main.js:163413
mountComponent @ main.js:163300
mountComponent @ main.js:169517
mountChildren @ main.js:168921
_createInitialChildren @ main.js:164753
mountComponent @ main.js:164572
mountComponent @ main.js:169517
mountChildren @ main.js:168921
_createInitialChildren @ main.js:164753
mountComponent @ main.js:164572
mountComponent @ main.js:169517
performInitialMount @ main.js:163413
mountComponent @ main.js:163300
mountComponent @ main.js:169517
performInitialMount @ main.js:163413
mountComponent @ main.js:163300
mountComponent @ main.js:169517
performInitialMount @ main.js:163413
mountComponent @ main.js:163300
mountComponent @ main.js:169517
performInitialMount @ main.js:163413
mountComponent @ main.js:163300
mountComponent @ main.js:169517
performInitialMount @ main.js:163413
mountComponent @ main.js:163300
mountComponent @ main.js:169517
performInitialMount @ main.js:163413
mountComponent @ main.js:163300
mountComponent @ main.js:169517
mountComponentIntoNode @ main.js:168253
perform @ main.js:172111
batchedMountComponentIntoNode @ main.js:168275
perform @ main.js:172111
batchedUpdates @ main.js:167336
batchedUpdates @ main.js:170277
_renderNewRootComponent @ main.js:168468
_renderSubtreeIntoContainer @ main.js:168550
render @ main.js:168571
(anonymous) @ main.js:5759
require.43../routes @ main.js:5765
s @ main.js:1
e @ main.js:1
(anonymous) @ main.js:1
main.js:209029 2017-11-02T11:39:35.322-0000 ERROR window.addWindowListener('error'): { isTrusted: [Getter] }
main.js:209029 2017-11-02T11:39:35.323-0000 ERROR window.onerror: Uncaught TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null [TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null]
TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null
    at Object.getClosestInstanceFromNode (http://localhost:8888/js/main.js:165191:11)
    at findParent (http://localhost:8888/js/main.js:167614:32)
    at handleTopLevelImpl (http://localhost:8888/js/main.js:167643:28)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:8888/js/main.js:172111:20)
    at Object.batchedUpdates (http://localhost:8888/js/main.js:167336:26)
    at Object.batchedUpdates (http://localhost:8888/js/main.js:170277:27)
    at dispatchEvent (http://localhost:8888/js/main.js:167723:20)
main.js:165191 Uncaught TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null
    at Object.getClosestInstanceFromNode (main.js:165191)
    at findParent (main.js:167614)
    at handleTopLevelImpl (main.js:167643)
    at ReactDefaultBatchingStrategyTransaction.perform (main.js:172111)
    at Object.batchedUpdates (main.js:167336)
    at Object.batchedUpdates (main.js:170277)
    at dispatchEvent (main.js:167723)
getClosestInstanceFromNode @ main.js:165191
findParent @ main.js:167614
handleTopLevelImpl @ main.js:167643
perform @ main.js:172111
batchedUpdates @ main.js:167336
batchedUpdates @ main.js:170277
dispatchEvent @ main.js:167723
main.js:209029 2017-11-02T11:39:35.328-0000 ERROR window.addWindowListener('error'): { isTrusted: [Getter] }
main.js:209029 2017-11-02T11:39:35.330-0000 ERROR window.onerror: Uncaught TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null [TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null]
TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null
    at Object.getClosestInstanceFromNode (http://localhost:8888/js/main.js:165191:11)
    at findParent (http://localhost:8888/js/main.js:167614:32)
    at handleTopLevelImpl (http://localhost:8888/js/main.js:167643:28)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:8888/js/main.js:172111:20)
    at Object.batchedUpdates (http://localhost:8888/js/main.js:167336:26)
    at Object.batchedUpdates (http://localhost:8888/js/main.js:170277:27)
    at dispatchEvent (http://localhost:8888/js/main.js:167723:20)
main.js:165191 Uncaught TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null
    at Object.getClosestInstanceFromNode (main.js:165191)
    at findParent (main.js:167614)
    at handleTopLevelImpl (main.js:167643)
    at ReactDefaultBatchingStrategyTransaction.perform (main.js:172111)
    at Object.batchedUpdates (main.js:167336)
    at Object.batchedUpdates (main.js:170277)
    at dispatchEvent (main.js:167723)
getClosestInstanceFromNode @ main.js:165191
findParent @ main.js:167614
handleTopLevelImpl @ main.js:167643
perform @ main.js:172111
batchedUpdates @ main.js:167336
batchedUpdates @ main.js:170277
dispatchEvent @ main.js:167723
main.js:209029 2017-11-02T11:39:35.334-0000 ERROR window.addWindowListener('error'): { isTrusted: [Getter] }
main.js:209029 2017-11-02T11:39:35.335-0000 ERROR window.onerror: Uncaught TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null [TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null]
TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null
    at Object.getClosestInstanceFromNode (http://localhost:8888/js/main.js:165191:11)
    at findParent (http://localhost:8888/js/main.js:167614:32)
    at handleTopLevelImpl (http://localhost:8888/js/main.js:167643:28)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:8888/js/main.js:172111:20)
    at Object.batchedUpdates (http://localhost:8888/js/main.js:167336:26)
    at Object.batchedUpdates (http://localhost:8888/js/main.js:170277:27)
    at dispatchEvent (http://localhost:8888/js/main.js:167723:20)
main.js:165191 Uncaught TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null
    at Object.getClosestInstanceFromNode (main.js:165191)
    at findParent (main.js:167614)
    at handleTopLevelImpl (main.js:167643)
    at ReactDefaultBatchingStrategyTransaction.perform (main.js:172111)
    at Object.batchedUpdates (main.js:167336)
    at Object.batchedUpdates (main.js:170277)
    at dispatchEvent (main.js:167723)
getClosestInstanceFromNode @ main.js:165191
findParent @ main.js:167614
handleTopLevelImpl @ main.js:167643
perform @ main.js:172111
batchedUpdates @ main.js:167336
batchedUpdates @ main.js:170277
dispatchEvent @ main.js:167723
main.js:209029 2017-11-02T11:39:35.339-0000 ERROR window.addWindowListener('error'): { isTrusted: [Getter] }
main.js:209029 2017-11-02T11:39:35.341-0000 ERROR window.onerror: Uncaught TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null [TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null]
TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null
    at Object.getClosestInstanceFromNode (http://localhost:8888/js/main.js:165191:11)
    at findParent (http://localhost:8888/js/main.js:167614:32)
    at handleTopLevelImpl (http://localhost:8888/js/main.js:167643:28)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:8888/js/main.js:172111:20)
    at Object.batchedUpdates (http://localhost:8888/js/main.js:167336:26)
    at Object.batchedUpdates (http://localhost:8888/js/main.js:170277:27)
    at dispatchEvent (http://localhost:8888/js/main.js:167723:20)
main.js:165191 Uncaught TypeError: Cannot read property '__reactInternalInstance$50f4gnbe9dd' of null
    at Object.getClosestInstanceFromNode (main.js:165191)
    at findParent (main.js:167614)
    at handleTopLevelImpl (main.js:167643)
    at ReactDefaultBatchingStrategyTransaction.perform (main.js:172111)
    at Object.batchedUpdates (main.js:167336)
    at Object.batchedUpdates (main.js:170277)
    at dispatchEvent (main.js:167723)
getClosestInstanceFromNode @ main.js:165191
findParent @ main.js:167614
handleTopLevelImpl @ main.js:167643
perform @ main.js:172111
batchedUpdates @ main.js:167336
batchedUpdates @ main.js:170277
dispatchEvent @ main.js:167723
```

**Comment by guylepage3** [comment]
I had the same issue and had to delete my wallet and virtual environment. cc: @larrysalibra @kantai

**Comment by wbobeirne** [comment]
This interface is no longer a part of the onboarding process.
