### ISSUE TITLE
Unable to verify Twitter account

### ISSUE THREAD

**Issue by sinzin91** [blockstack/blockstack-browser#1028]
On `v0.19.1`, I attempted to verify my Twitter account, but see this error in the JS console after clicking "Verify":

```
2017-11-02T23:33:15.459-0700 ERROR window.addWindowListener('error'): { isTrusted: [Getter] }
main.js:208983 2017-11-02T23:33:15.460-0700 ERROR window.onerror: Uncaught TypeError: state.localIdentities.slice is not a function [TypeError: state.localIdentities.slice is not a function]
TypeError: state.localIdentities.slice is not a function
    at IdentityReducer (http://localhost:8888/js/main.js:14468:56)
    at combination (http://localhost:8888/js/main.js:192645:29)
    at combination (http://localhost:8888/js/main.js:192645:29)
    at RootReducer (http://localhost:8888/js/main.js:15830:10)
    at computeNextEntry (http://localhost:8888/js/main.js:189937:21)
    at recomputeStates (http://localhost:8888/js/main.js:189971:17)
    at http://localhost:8888/js/main.js:190355:22
    at Object.dispatch (http://localhost:8888/js/main.js:192871:22)
    at dispatch (http://localhost:8888/js/main.js:190404:19)
    at http://localhost:8888/js/main.js:192391:16
main.js:14468 Uncaught TypeError: state.localIdentities.slice is not a function
    at IdentityReducer (main.js:14468)
    at combination (main.js:192645)
    at combination (main.js:192645)
    at RootReducer (main.js:15830)
    at computeNextEntry (main.js:189937)
    at recomputeStates (main.js:189971)
    at main.js:190355
    at Object.dispatch (main.js:192871)
    at dispatch (main.js:190404)
    at main.js:192391
```

**Comment by larrysalibra** [comment]
You'll need to reset your browser from the settings menu and then restore from your keychain phrase. @sinzin91 please let us know if this works for you!
