### ISSUE TITLE
Periodic code signing errors on macOS

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#1262]
I'm getting periodic code signing errors in the macOS build process during the export phase. Running it again usually fixes it. Opening an issue in case @yknl or anyone else experiences this. 

I'm using Xcode Version 9.2 (9C40b) on macOS 10.13.3 (17D102)

```
[18:43:02] Finished 'buildMacReleaseArchive' after 1.13 min
[18:43:02] Starting 'buildMacReleaseExport'...
2018-03-29 18:43:03.955 xcodebuild[16482:2245375] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/nf/ylp1ctks7c11dfpdly8pv_980000gn/T/Blockstack_2018-03-29_18-43-03.954.xcdistributionlogs'.
2018-03-29 18:43:38.710 xcodebuild[16482:2245375] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7fcbe4ea7d30>: Error Domain=IDEDistributionPipelineErrorDomain Code=0 "Code signing "libswiftDarwin.dylib" failed." UserInfo={NSLocalizedDescription=Code signing "libswiftDarwin.dylib" failed., NSLocalizedRecoverySuggestion=View distribution logs for more information.}
error: exportArchive: Code signing "libswiftDarwin.dylib" failed.

Error Domain=IDEDistributionPipelineErrorDomain Code=0 "Code signing "libswiftDarwin.dylib" failed." UserInfo={NSLocalizedDescription=Code signing "libswiftDarwin.dylib" failed., NSLocalizedRecoverySuggestion=View distribution logs for more information.}

** EXPORT FAILED **

[18:43:38] 'buildMacReleaseExport' errored after 36 s
[18:43:38] Error: Command `xcodebuild -archivePath ./native/macos/archive/Blockstack.xcarchive -exportOptionsPlist ./native/macos/Blockstack/export.plist -exportArchive -exportPath ./native/macos/export/` failed with exit code 70
    at ChildProcess.exithandler (child_process.js:198:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:920:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
[18:43:38] 'mac-release' errored after 3.62 min
[18:43:38] Error in plugin 'run-sequence(buildMacReleaseExport)'
Message:
    Command `xcodebuild -archivePath ./native/macos/archive/Blockstack.xcarchive -exportOptionsPlist ./native/macos/Blockstack/export.plist -exportArchive -exportPath ./native/macos/export/` failed with exit code 70
Details:
    killed: false
    code: 70
    signal: null
    cmd: xcodebuild -archivePath ./native/macos/archive/Blockstack.xcarchive -exportOptionsPlist ./native/macos/Blockstack/export.plist -exportArchive -exportPath ./native/macos/export/
    stdout: ** EXPORT FAILED **


    stderr: 2018-03-29 18:43:03.955 xcodebuild[16482:2245375] [MT] IDEDistribution: -[IDEDistributionLogging _createLoggingBundleAtPath:]: Created bundle at path '/var/folders/nf/ylp1ctks7c11dfpdly8pv_980000gn/T/Blockstack_2018-03-29_18-43-03.954.xcdistributionlogs'.
2018-03-29 18:43:38.710 xcodebuild[16482:2245375] [MT] IDEDistribution: Step failed: <IDEDistributionPackagingStep: 0x7fcbe4ea7d30>: Error Domain=IDEDistributionPipelineErrorDomain Code=0 "Code signing "libswiftDarwin.dylib" failed." UserInfo={NSLocalizedDescription=Code signing "libswiftDarwin.dylib" failed., NSLocalizedRecoverySuggestion=View distribution logs for more information.}
error: exportArchive: Code signing "libswiftDarwin.dylib" failed.

Error Domain=IDEDistributionPipelineErrorDomain Code=0 "Code signing "libswiftDarwin.dylib" failed." UserInfo={NSLocalizedDescription=Code signing "libswiftDarwin.dylib" failed., NSLocalizedRecoverySuggestion=View distribution logs for more information.}


Stack:
Error: Command `xcodebuild -archivePath ./native/macos/archive/Blockstack.xcarchive -exportOptionsPlist ./native/macos/Blockstack/export.plist -exportArchive -exportPath ./native/macos/export/` failed with exit code 70
```

**Comment by markmhx** [comment]
Are you still encountering this, @larrysalibra?

**Comment by larrysalibra** [comment]
I haven't tried to build the macOS release for at least 6-9 months. @yknl would be a better person to ask.

**Comment by yknl** [comment]
Haven't experienced this. The build process has also changed quite a bit since this issue was opened. I think this is good to close.
