### ISSUE TITLE
CORS proxy fails to fetch in macOS Safari and mobile Safari

### ISSUE THREAD

**Issue by yknl** [blockstack/blockstack-browser#1638]
Social proof verification request fails to fetch due to access control checks:
![image](https://user-images.githubusercontent.com/29081231/44805506-6c93ca80-ab92-11e8-8e07-eab880def972.png)

**Comment by combatmonk** [comment]
OSX Mojave:
10.14.3 (18D109)
Added to FW exceptions.
Brand New Install On Launch:


Blockstack Error: CORS proxy was terminated

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
Emitted 'error' event at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1468:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:17)
