### ISSUE TITLE
Logging into helloblockstack.com fails

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#475]
Logging in to https://helloblockstack.com currently fails now that we've added core auth tokens.

This is because helloblockstack.com sets `app_domain` in the `authRequest` to the origin of the page (ie. `windows.location.origin`) whereas Blockstack Core expects only the name + tld.

@shea256 @jcnelson Which one is the intended behavior? origin or domain name?

This is the error from Core's `api_endpoint.log`:
```
[2017-05-16 05:15:20,927] [DEBUG] [app:100] (1383.140736736195520) Not a valid token
[2017-05-16 05:15:20,934] [DEBUG] [rpc:3291] (1383.140736736195520) Authenticated with password
[2017-05-16 05:15:20,955] [ERROR] [rpc:430] (1383.140736736195520) u'https://helloblockstack.com' does not match '^([a-zA-Z0-9\\-_.~%/]+)$'

Failed validating 'pattern' in schema['properties']['app_domain']:
    {'pattern': '^([a-zA-Z0-9\\-_.~%/]+)$', 'type': 'string'}

On instance['app_domain']:
    u'https://helloblockstack.com'
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 427, in GET_auth
    jsonschema.validate(decoded_token['payload'], APP_AUTHREQUEST_SCHEMA )
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: u'https://helloblockstack.com' does not match '^([a-zA-Z0-9\\-_.~%/]+)$'

Failed validating 'pattern' in schema['properties']['app_domain']:
    {'pattern': '^([a-zA-Z0-9\\-_.~%/]+)$', 'type': 'string'}

On instance['app_domain']:
    u'https://helloblockstack.com'
[2017-05-16 05:15:20,959] [DEBUG] [rpc:434] (1383.140736736195520) Invalid token
127.0.0.1 - - [16/May/2017 05:15:20] "GET /v1/auth?authRequest=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJhcHBfZG9tYWluIjoiaHR0cHM6Ly9oZWxsb2Jsb2Nrc3RhY2suY29tIiwibWV0aG9kcyI6W10sImFwcF9wdWJsaWNfa2V5IjoiMDMxNjU1OWJkMGU0OThkYTNmNDJmNmJmMDM0Y2I1Y2NjY2U5NTMyZjZlYjI3NjEwYTY5YjE2YTE1MGYyNjg5NmVmIiwiYmxvY2tjaGFpbl9pZHMiOlsiZGV2bmFtZTIuaWQiXX0.QaPklvgFoCrTxrbqgsP1PklOS84D2drNkryL6Jl6YLCdeSDXE4koeNpgCI4tW1iL-tkN--Xx4tuLTdPOBv6Awg HTTP/1.1" 401 -
[2017-05-16 05:17:33,382] [DEBUG] [registrar:927] (1383.12
```

**Comment by jcnelson** [comment]
it should be just the domain name (`helloblockstack.com`).

**Comment by larrysalibra** [comment]
Fixed
