### ISSUE TITLE
Timeouts and Hangs on Auth Requests

### ISSUE THREAD

**Issue by kantai** [blockstack/blockstack-browser#542]
It looks like when Auth Requests fail with a pattern validation error returning a 401, the next attempted request isn't sent (or, at least not received by Core) for ~20 seconds at times.

Logs look something like this:

```
[2017-06-20 15:15:17,710] [DEBUG] [rpc:3269] (10222.140736036320192) 
full path: /v1/auth?authRequest=hexFOO
referer: http://localhost:8888/auth?authRequest=hexFOO
authorization: bearer 

[2017-06-20 15:15:17,717] [DEBUG] [app:100] (10222.140736036320192) Not a valid token
[2017-06-20 15:15:17,745] [DEBUG] [rpc:3291] (10222.140736036320192) Authenticated with password
[2017-06-20 15:15:17,752] [ERROR] [rpc:430] (10222.140736036320192) u'http://localhost:3000' does not match '^([a-zA-Z0-9\\-_.~%/]+)$'

Failed validating 'pattern' in schema['properties']['app_domain']:
    {'pattern': '^([a-zA-Z0-9\\-_.~%/]+)$', 'type': 'string'}

On instance['app_domain']:
    u'http://localhost:3000'
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 427, in GET_auth
    jsonschema.validate(decoded_token['payload'], APP_AUTHREQUEST_SCHEMA )
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: u'http://localhost:3000' does not match '^([a-zA-Z0-9\\-_.~%/]+)$'

Failed validating 'pattern' in schema['properties']['app_domain']:
    {'pattern': '^([a-zA-Z0-9\\-_.~%/]+)$', 'type': 'string'}

On instance['app_domain']:
    u'http://localhost:3000'
[2017-06-20 15:15:17,754] [DEBUG] [rpc:434] (10222.140736036320192) Invalid token
127.0.0.1 - - [20/Jun/2017 15:15:17] "GET /v1/auth?authRequest=hexFOO HTTP/1.1" 401 -
...
upgrade-insecure-requests: 1

[2017-06-20 15:15:42,453] [DEBUG] [rpc:316] (10222.140736036320192) No authorization header
[2017-06-20 15:15:42,457] [INFO] [rpc:3309] (10222.140736036320192) Failed to authenticate caller
127.0.0.1 - - [20/Jun/2017 15:15:42] "GET /v1/auth?authRequest=hexFOO HTTP/1.1" 403 -
```

Will look into duplicating this error, and then see whether we can blame Core or Browser.

**Comment by guylepage3** [comment]
@kantai is this still an issue? can we `backlog` this?

**Comment by kantai** [comment]
I haven't experienced this issue since then, but I haven't made any changes to core related to the issue.

**Comment by guylepage3** [comment]
@kantai ok. so we should keep this open and assign it to @larrysalibra?

**Comment by kantai** [comment]
I'll look into it before the next milestone, and close it if I can't replicate.

**Comment by guylepage3** [comment]
Ok. adding this to this sprint then.

**Comment by larrysalibra** [comment]
Core was expecting a domain name instead of an origin in `app_domain` - this was fixed in core a while back.
