### ISSUE TITLE
unable to sign in to hello blockstack app

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#547]
When using the latest version of the blockstack browser, I am unable to sign in to the Hello, Blockstack app.

<img width="722" alt="screenshot 2017-06-21 19 09 57" src="https://user-images.githubusercontent.com/1711854/27410439-9829f288-56b5-11e7-89e8-8a1cf1f69042.png">

<img width="606" alt="screenshot 2017-06-21 19 10 46" src="https://user-images.githubusercontent.com/1711854/27410444-9c6c02a0-56b5-11e7-8a55-7bd3ff680618.png">

```
main.js:153900 2017-06-21T19:09:39.567-0400 INFO utils/logging-utils.js: Logging system enabled
main.js:153900 2017-06-21T19:09:39.581-0400 INFO utils/logging-utils.js: Log server: http://localhost:8333/
main.js:153900 2017-06-21T19:09:39.581-0400 TRACE index.js: NODE_ENV is not production
main.js:153900 2017-06-21T19:09:39.581-0400 DEBUG index.js: Enabling React devtools
main.js:153900 2017-06-21T19:09:39.593-0400 TRACE App.js: componentWillMount
main.js:153900 2017-06-21T19:09:39.624-0400 TRACE App.js: performSanityChecks
main.js:153900 2017-06-21T19:09:39.625-0400 DEBUG store/sanity/actions.js: isCoreRunning: http://localhost:6270/v1/node/ping
main.js:153900 2017-06-21T19:09:39.626-0400 DEBUG utils/api-utils.js: isCoreApiRunning: http://localhost:6270/v1/node/ping
main.js:153900 2017-06-21T19:09:39.626-0400 DEBUG store/sanity/actions.js: isCoreApiPasswordValid: http://localhost:6270/v1/wallet/payment_address
main.js:153900 2017-06-21T19:09:39.627-0400 DEBUG utils/api-utils.js: isApiPasswordValid: http://localhost:6270/v1/wallet/payment_address
main.js:153900 2017-06-21T19:09:39.627-0400 ERROR App.js: Sanity check: Error! Core API is NOT running!
main.js:153900 2017-06-21T19:09:39.628-0400 ERROR App.js: Sanity check: Error! Core API password is wrong!
main.js:153900 2017-06-21T19:09:39.730-0400 ERROR App.js: Sanity check: Error! Core API is NOT running!
main.js:153900 2017-06-21T19:09:39.731-0400 ERROR App.js: Sanity check: Error! Core API password is wrong!
main.js:153900 2017-06-21T19:09:41.768-0400 ERROR window.addWindowListener('error'): { isTrusted: [Getter] }
main.js:153900 2017-06-21T19:09:41.770-0400 ERROR window.onerror: Uncaught Error: Expected UInt31, got Number -186964252 [Error: Expected UInt31, got Number -186964252]
main.js:108155 Uncaught TfTypeErrormessage: (...)__error: Error
    at new TfTypeError (http://localhost:8888/js/main.js:147602:24)
    at typeforce (http://localhost:8888/js/main.js:147993:11)
    at HDNode.deriveHardened (http://localhost:8888/js/main.js:31818:3)
    at AppsNode.getAppNode (http://localhost:8888/js/main.js:10806:33)
    at AuthModal.login (http://localhost:8888/js/main.js:2692:38)
    at Object.invokeGuardedCallback (http://localhost:8888/js/main.js:108130:5)
    at executeDispatch (http://localhost:8888/js/main.js:102165:21)
    at Object.executeDispatchesInOrder (http://localhost:8888/js/main.js:102185:7)
    at executeDispatchesAndRelease (http://localhost:8888/js/main.js:101590:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8888/js/main.js:101601:10)__type: function UInt31(value)__value: -186964252__valueTypeName: undefinedget message: function ()__proto__: Error
main.js:153900 2017-06-21T19:09:48.806-0400 ERROR window.addWindowListener('error'): { isTrusted: [Getter] }
main.js:153900 2017-06-21T19:09:48.807-0400 ERROR window.onerror: Uncaught Error: Expected UInt31, got Number -186964252 [Error: Expected UInt31, got Number -186964252]
main.js:108155 Uncaught TfTypeErrormessage: (...)__error: Error
    at new TfTypeError (http://localhost:8888/js/main.js:147602:24)
    at typeforce (http://localhost:8888/js/main.js:147993:11)
    at HDNode.deriveHardened (http://localhost:8888/js/main.js:31818:3)
    at AppsNode.getAppNode (http://localhost:8888/js/main.js:10806:33)
    at AuthModal.login (http://localhost:8888/js/main.js:2692:38)
    at Object.invokeGuardedCallback (http://localhost:8888/js/main.js:108130:5)
    at executeDispatch (http://localhost:8888/js/main.js:102165:21)
    at Object.executeDispatchesInOrder (http://localhost:8888/js/main.js:102185:7)
    at executeDispatchesAndRelease (http://localhost:8888/js/main.js:101590:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8888/js/main.js:101601:10)__type: function UInt31(value)__value: -186964252__valueTypeName: undefinedget message: function ()__proto__: Error
main.js:153900 2017-06-21T19:10:06.028-0400 TRACE utils/api-utils.js: isCoreApiRunning? Yes!
main.js:153900 2017-06-21T19:10:06.030-0400 ERROR App.js: Sanity check: Error! Core API is NOT running!
main.js:153900 2017-06-21T19:10:06.031-0400 ERROR App.js: Sanity check: Error! Core API password is wrong!
main.js:153900 2017-06-21T19:10:06.061-0400 TRACE utils/api-utils.js: isCoreApiPasswordValid? Yes!
main.js:153900 2017-06-21T19:10:06.062-0400 DEBUG store/sanity/actions.js: isCoreApiPasswordValid? Yes!
main.js:153900 2017-06-21T19:10:06.064-0400 DEBUG App.js: Sanity check: Core API endpoint is running!
main.js:153900 2017-06-21T19:10:06.065-0400 ERROR App.js: Sanity check: Error! Core API password is wrong!
```

**Comment by shea256** [comment]
I've been having the same issue. I sent my `api_endpoint.log` file to @larrysalibra so he can take a look.

**Comment by larrysalibra** [comment]
@guylepage3 when you say “latest version” are you talking about the latest public release (`v0.9.1`), on `HEAD` of `v0.10` or the `v0.10.0-alpha.2` version I distributed privately? Alpha.2 has this problem, v0.9.1 should not have it (because we weren’t generating app keys yet) and `HEAD` of `v0.10` should not have the problem either (it was fixed a day or so ago).

@shea256 Are you seeing the same error @guylepage3  has pasted in the log above? Which version are you using? The current release,`v0.9.1`?

Your `api_endpoint.log` shows a broken pipe issue with core:

```
[2017-06-21 19:14:38,450] [DEBUG] [app:100] (5089.140736321590208) Not a valid token
[2017-06-21 19:14:38,454] [DEBUG] [rpc:3291] (5089.140736321590208) Authenticated with password
[2017-06-21 19:14:38,482] [DEBUG] [rpc:447] (5089.140736321590208) Verify with —redacted—
127.0.0.1 - - [21/Jun/2017 19:14:38] "GET /v1/auth?authRequest=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJhcHBfZG9tYWluIjoiaGVsbG9ibG9ja3N0YWNrLmNvbSIsIm1ldGhvZHMiOltdLCJhcHBfcHVibGljX2tleSI6IjAyNzdkMzc3MmNjMGFjZjUwZWM0ZTdiYTQzYTlhYzE2NWE4MjE1Mjc1ZWY5ZGNjZmM3YWZkZDhmZWU0NmM0MjcwNSJ9.dkiYZfWbGSWj3laaukH-wEKMqaK_cZ8N2tnQavnXKg3K_FYNjUm3pg8dhszydqQNODqG5lO5K39LmtmRhkFfiw HTTP/1.1" 200 -
[2017-06-21 19:14:38,646] [ERROR] [rpc:3320] (5089.140736321590208) [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 3317, in _dispatch
    return route_method( session, path_info, *route_args )
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 461, in GET_auth
    return self._reply_json({'token': res['session_token']})
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 191, in _reply_json
    self._send_headers(status_code=status_code)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 181, in _send_headers
    self.send_response(status_code)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 396, in send_response
    self.send_header('Date', self.date_time_string())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 401, in send_header
    self.wfile.write("%s: %s\r\n" % (keyword, value))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 328, in write
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
127.0.0.1 - - [21/Jun/2017 19:14:38] "GET /v1/auth?authRequest=eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NksifQ.eyJhcHBfZG9tYWluIjoiaGVsbG9ibG9ja3N0YWNrLmNvbSIsIm1ldGhvZHMiOltdLCJhcHBfcHVibGljX2tleSI6IjAyNzdkMzc3MmNjMGFjZjUwZWM0ZTdiYTQzYTlhYzE2NWE4MjE1Mjc1ZWY5ZGNjZmM3YWZkZDhmZWU0NmM0MjcwNSJ9.dkiYZfWbGSWj3laaukH-wEKMqaK_cZ8N2tnQavnXKg3K_FYNjUm3pg8dhszydqQNODqG5lO5K39LmtmRhkFfiw HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 657, in __init__
    self.finish()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 716, in finish
    self.wfile.close()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 283, in close
    self.flush()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 307, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
```

Before I open an issue on Core about this, I want to make sure to know which version is having this problem. Thanks!

**Comment by guylepage3** [comment]
>when you say “latest version” are you talking about the latest public release (v0.9.1), on HEAD of v0.10 or the v0.10.0-alpha.2 version I distributed privately?

@larrysalibra I am running the `v0.10.0-alpha.2` that you distributed privately.

**Comment by larrysalibra** [comment]
@guylepage3 That version is just for the bundled core node. This problem should be fixed in `v0.10`. It's not fixed in the browser bundled with `v0.10.0-alpha2`. Please let me know if you're seeing the problem in `v0.10` as well.

**Comment by guylepage3** [comment]
will do. checking now.

**Comment by guylepage3** [comment]
hmm.. i am getting the same issue using `v0.10`

**Comment by pstan26** [comment]
@larrysalibra same here. Love that a modal pops up to allow me to sign in to Hello Blockstack, but nothing happens when I click `approve`. This basic app obviously _needs_ to work properly, otherwise developers could take it as a sign that even the most basic app, and thus the platform itself, doesn't work.
![screen shot 2017-06-27 at 12 56 06 am](https://user-images.githubusercontent.com/5605552/27571422-966cdf9c-5ad3-11e7-9abc-54168cb73de0.png)

**Comment by larrysalibra** [comment]
Thanks for reporting! You’re probably experiencing this problem because you have stale state. Try in incognito or after clearing local storage to work around.

These problems will go away once we start migrating state (see #562)

**Comment by guylepage3** [comment]
closing issue
