### ISSUE TITLE
Verify token error when profile goes from pending to registered

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-browser#572]
```
Error: Token issuer public key does not match the verifying value
    at verifyToken (http://localhost:3000/js/main.js:11944:11)
    at verifyTokenRecord (http://localhost:3000/js/main.js:11971:22)
    at http://localhost:3000/js/main.js:11985:22
    at Array.map (native)
    at getProfileFromTokens (http://localhost:3000/js/main.js:11979:16)
    at http://localhost:3000/js/main.js:12211:62
    at <anonymous>
```

**Comment by jackzampolin** [comment]
This bug isn't present in the latest versions. Closing as stale.
