### ISSUE TITLE
unable to view profile after username accepted

### ISSUE THREAD

**Issue by guylepage3** [blockstack/blockstack-browser#575]
I'm unable to view my profile after the username was accepted.

<img width="1249" alt="screenshot 2017-06-28 16 41 21" src="https://user-images.githubusercontent.com/1711854/27659467-90bdde76-5c21-11e7-8924-d37a425eb6a2.png">

**Comment by guylepage3** [comment]
@larrysalibra emailing you my logs for this.

**Comment by guylepage3** [comment]
whoa file is 165MB. I'll upload it to Dropbox and share it with you instead.

**Comment by larrysalibra** [comment]
I can replicate the problem. Working on a fix.

```
profiles/store/identity/actions.js: fetchCurrentIdentity: papriika.id resolveZoneFileToProfile: error [TypeError: Cannot read property 'label' of undefined]
TypeError: Cannot read property 'label' of undefined
    at SocialAccountItem.render (http://localhost:8888/js/main.js:7093:57)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://localhost:8888/js/main.js:104502:30)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://localhost:8888/js/main.js:104525:32)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8888/js/main.js:104065:30)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8888/js/main.js:103961:21)
    at Object.mountComponent (http://localhost:8888/js/main.js:110260:35)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:8888/js/main.js:104074:34)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:8888/js/main.js:103961:21)
    at Object.mountComponent (http://localhost:8888/js/main.js:110260:35)
    at ReactDOMComponent.mountChildren (http://localhost:8888/js/main.js:109648:4
```

**Comment by larrysalibra** [comment]
The problem was that we started using the accounts field in the profile that in the past was used to store your social accounts to also store a link to the index file for Gaia. I've made changes to the rendering code that should fix the problem that was blocking you. 

In the meantime, I'll coordinate with @jcnelson to see if we can find a better place for Gaia related meta data as we redesign the token file.

**Comment by guylepage3** [comment]
Thank you very much @larrysalibra. 😄 

So this should be resolved in the next release? Or in the next patch?

**Comment by larrysalibra** [comment]
It should be resolved in the `v0.11` right now. We’ll work on the token file format and the use of `accounts` for storage data as we work on multi player storage

**Comment by guylepage3** [comment]
@larrysalibra cool. i'll import the account on the `v0.11` branch today and test it out.

**Comment by guylepage3** [comment]
Whoot! Success @larrysalibra. I can see my profile now that I'm running `v0.11`. Thank you sir.

Closing issue.
