### ISSUE TITLE
Error in sign in approval process

### ISSUE THREAD

**Issue by shea256** [blockstack/blockstack-browser#600]
I click the button to approve a sign in request, but then nothing happens. It seems there's an error being thrown here.

Here are the console log errors:

<img width="607" alt="screen shot 2017-07-06 at 5 30 04 pm" src="https://user-images.githubusercontent.com/994646/27933789-d847e73c-6270-11e7-944e-67035ee07691.png">

Here's the screen I'm on:

<img width="477" alt="screen shot 2017-07-06 at 5 30 52 pm" src="https://user-images.githubusercontent.com/994646/27933817-ef40f834-6270-11e7-921c-1b5cfbc55199.png">

**Comment by larrysalibra** [comment]
@shea256 I suspected that your state is missing one of the private keys that's generated at account creation.

It looks very similar to: https://github.com/blockstack/blockstack-browser/issues/547

We don't currently migrate localstorage state between pre-release builds: https://github.com/blockstack/blockstack-browser/issues/547

Does this problem happen with a clean localstorage?

If so, what are the steps that you took to generate this problem?

**Comment by shea256** [comment]
I'm having this problem again. I cleared localStorage and started over. I then registered a profile and attached a name to it. I'm now waiting for the registration to go through. But in the meantime, sign in is not working.

Here's a screenshot:

<img width="1653" alt="screen shot 2017-07-14 at 12 17 49 pm" src="https://user-images.githubusercontent.com/994646/28220779-c90ca52c-688e-11e7-943a-a2f5d326c2e8.png">

I can post more logs if needed.

**Comment by larrysalibra** [comment]
@shea256 your core api endpoint is replying with a `500` error when browser is trying to set the storage settings (part of the sign in process). Can you share you `api_endpoint.log` with me (privately)?    It'll be in `~/Library/Application Support/Blockstack/config/api_endpoint.log`

**Comment by shea256** [comment]
@larrysalibra Yes I'll DM you.

**Comment by larrysalibra** [comment]
@shea256 Your core node is having trouble connecting to dropbox's API.

It happened twice while trying to create the storage index in dropbox:

Are you on an unreliable or really slow network connection?  It appears that the timeout is set to 30 seconds.  Another possibility is that dropbox's  API went down for a while.

tagging @jcnelson and @kantai to see if they've seen similar behavior

```
[2017-07-14 12:16:04,418] [DEBUG] [app:113] (40340.123145346932736) Not a valid token
[2017-07-14 12:16:04,423] [DEBUG] [rpc:3543] (40340.123145346932736) Authenticated with password
[2017-07-14 12:16:04,430] [DEBUG] [rpc:2392] (40340.123145346932736) Updating driver config for dropbox
[2017-07-14 12:16:04,438] [DEBUG] [rpc:2398] (40340.123145346932736) Set up config and index driver dropbox system-wide
[2017-07-14 12:16:04,446] [DEBUG] [config:881] (40340.123145346932736) Override blockstack-client.port from 6264 to 6264
[2017-07-14 12:16:04,460] [DEBUG] [common:105] (40320) Non-concurrent operation in progress: 'index_setup'
[2017-07-14 12:16:04,461] [DEBUG] [common:374] (40320) Make index bucket /index/0
[2017-07-14 12:16:06,903] [DEBUG] [dropbox:97] (40340) /index/0 available at https://www.dropbox.com/s/vt8xekq8ibhfgc7/0?dl=1
[2017-07-14 12:16:06,907] [DEBUG] [common:374] (40320) Make index bucket /index/1
[2017-07-14 12:16:09,412] [DEBUG] [dropbox:97] (40340) /index/1 available at https://www.dropbox.com/s/h6wp6accrbtj88l/1?dl=1
[2017-07-14 12:16:09,416] [DEBUG] [common:374] (40320) Make index bucket /index/2
[2017-07-14 12:16:11,716] [DEBUG] [dropbox:97] (40340) /index/2 available at https://www.dropbox.com/s/hhrsdsr4erad0dd/2?dl=1
[2017-07-14 12:16:11,720] [DEBUG] [common:374] (40320) Make index bucket /index/3
[2017-07-14 12:16:41,727] [ERROR] [dropbox:101] (40340) HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/upload (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x102cf3750>, 'Connection to content.dropboxapi.com timed out. (connect timeout=30)'))
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/drivers/dropbox.py", line 91, in dropbox_put_chunk
    file_info = dbx.files_upload(chunk_buf, name, mode=dropbox.files.WriteMode('overwrite'))
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/dropbox/base.py", line 1267, in files_upload
    f,
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/upload (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x102cf3750>, 'Connection to content.dropboxapi.com timed out. (connect timeout=30)'))
[2017-07-14 12:16:41,727] [ERROR] [dropbox:103] (40340) Failed to save 28 bytes to /index/3 in Dropbox
[2017-07-14 12:16:41,728] [ERROR] [common:384] (40320) 
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/drivers/common.py", line 380, in index_make_bucket
    assert url
AssertionError
[2017-07-14 12:16:41,728] [ERROR] [common:386] (40320) Failed to make bucket /index/3
[2017-07-14 12:16:41,728] [ERROR] [common:514] (40320) Failed to create bucket /index/3
[2017-07-14 12:16:41,728] [DEBUG] [common:111] (40320) Finished non-concurrent operation: 'index_setup'
[2017-07-14 12:16:41,728] [ERROR] [dropbox:192] (40340) Failed to set up index
127.0.0.1 - - [14/Jul/2017 12:16:41] "POST /v1/node/drivers/storage/dropbox?index=1 HTTP/1.1" 500 -
[2017-07-14 12:17:01,642] [DEBUG] [rpc:3521] (40340.123145321693184) 
full path: /v1/node/drivers/storage/dropbox?index=1
```

```
ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1020c0650>, 'Connection to content.dropboxapi.com timed out. (connect timeout=30)'))
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/drivers/dropbox.py", line 91, in dropbox_put_chunk
    file_info = dbx.files_upload(chunk_buf, name, mode=dropbox.files.WriteMode('overwrite'))
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/dropbox/base.py", line 1267, in files_upload
    f,
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/dropbox/dropbox.py", line 234, in request
    timeout=timeout)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/dropbox/dropbox.py", line 325, in request_json_string_with_retry
    timeout=timeout)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/dropbox/dropbox.py", line 409, in request_json_string
    timeout=timeout,
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/requests/sessions.py", line 549, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/requests/sessions.py", line 502, in request
    resp = self.send(prep, **send_kwargs)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/requests/sessions.py", line 612, in send
    r = adapter.send(request, **kwargs)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='content.dropboxapi.com', port=443): Max retries exceeded with url: /2/files/upload (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x1020c0650>, 'Connection to content.dropboxapi.com timed out. (connect timeout=30)'))
[2017-07-14 12:17:41,172] [ERROR] [dropbox:103] (40340) Failed to save 28 bytes to /index/4 in Dropbox
[2017-07-14 12:17:41,172] [ERROR] [common:384] (40320) 
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/backend/drivers/common.py", line 380, in index_make_bucket
    assert url
AssertionError
[2017-07-14 12:17:41,172] [ERROR] [common:386] (40320) Failed to make bucket /index/4
[2017-07-14 12:17:41,172] [ERROR] [common:514] (40320) Failed to create bucket /index/4
[2017-07-14 12:17:41,173] [DEBUG] [common:111] (40320) Finished non-concurrent operation: 'index_setup'
[2017-07-14 12:17:41,173] [ERROR] [dropbox:192] (40340) Failed to set up index
127.0.0.1 - - [14/Jul/2017 12:17:41] "POST /v1/node/drivers/storage/dropbox?index=1 HTTP/1.1" 500 -
[2017-07-14 12:17:56,331] [DEBUG] [rpc:3521] (40340.123145321693184) 
full path: /v1/node/ping
method: GET
```

**Comment by shea256** [comment]
@larrysalibra Well my connection is very good although I am tethering on my phone. My connection seems reliable and can handle video streaming.

**Comment by kantai** [comment]
What are people thoughts on letting storage build the index asynchronously, while the auth request is handled synchronously? 

The user would be brought to the app much more quickly, but the app wouldn't be able to interact with storage yet.

**Comment by jcnelson** [comment]
@kantai I think this already happens in the Browser when you connect your storage provider (@larrysalibra can confirm).  The trouble is, if the indexing process fails for some reason, the app (or the Browser) needs a way to learn this and inform the user to try again.

**Comment by larrysalibra** [comment]
@kantai 
> What are people thoughts on letting storage build the index asynchronously, while the auth request is handled synchronously?

There are a couple things going on here:

It looks like from the log, that the index failed to great when @shea256 connected storage.

Because of this, when logging in, it tried to create the index again (we call the function to set storage at log in too, because Core loses the dropbox token when we stop and restart it)

On this second call, creating the index failed again.

@jcnelson Is right - browser already lets storage initialize asynchronously at connection of storage, but have no mechanism to notify the user if it fails. It's trying again at log in because it detects that storage isn't initialized.  

> The user would be brought to the app much more quickly, but the app wouldn't be able to interact with storage yet.

The problem with this, is that it can take a very log time - on the order of minutes - to initialize storage. It will add a lot of complexity to apps if they can't start using storage until some indeterminate time in the future.

**Comment by kantai** [comment]
>The problem with this, is that it can take a very log time - on the order of minutes - to initialize storage. It will add a lot of complexity to apps if they can't start using storage until some indeterminate time in the future.

Okay, fair enough. So the solution, then, is to show some kind of warning to the user that their storage failed to initialize and they can't login to apps until it succeeds?

**Comment by jackzampolin** [comment]
This has been fixed in later versions. Closing as stale.
