### ISSUE TITLE
bufferutil undefined osx

### ISSUE THREAD

**Issue by bmcqueen** [blockstack/blockstack-browser#700]
Core is up and running, the proxy is running, but "gulp dev" fails near the end with an undefined error.  I'm running OSX Sierra 10.12.6, node version 3.10.8.

```
.
.
.
[15:37:03] Finished 'browserSync' after 34 ms
[15:37:03] Starting 'watch'...
[15:37:03] Finished 'watch' after 130 ms
[15:37:03] Finished 'dev' after 21 s
[Browsersync] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.1.112:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.112:3001
 --------------------------------------
[Browsersync] Serving files from: ./build/
/Users/bmcqueen/git/blockstack-browser/node_modules/ws/lib/Receiver.js:306
  if (mask != null && buf != null) bufferUtil.unmask(buf, mask);
                                             ^

TypeError: Cannot read property 'unmask' of undefined
    at Receiver.unmask (/Users/bmcqueen/git/blockstack-browser/node_modules/ws/lib/Receiver.js:306:46)
    at Receiver.finish (/Users/bmcqueen/git/blockstack-browser/node_modules/ws/lib/Receiver.js:505:25)
    at Receiver.expectHandler (/Users/bmcqueen/git/blockstack-browser/node_modules/ws/lib/Receiver.js:493:33)
    at Receiver.add (/Users/bmcqueen/git/blockstack-browser/node_modules/ws/lib/Receiver.js:103:24)
    at Socket.realHandler (/Users/bmcqueen/git/blockstack-browser/node_modules/ws/lib/WebSocket.js:825:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:551:20)
(default) bmcqueen:blockstack-browser bmcqueen$
```

BufferUtil is installed. 

```
(default) bmcqueen:blockstack-browser bmcqueen$ find . -type d |grep -i bufferutil
./node_modules/bufferutil
./node_modules/bufferutil/build
./node_modules/bufferutil/build/Release
./node_modules/bufferutil/node_modules
./node_modules/bufferutil/node_modules/nan
./node_modules/bufferutil/node_modules/nan/doc
./node_modules/bufferutil/node_modules/nan/tools
./node_modules/bufferutil/src
./node_modules/ws/node_modules/bufferutil
./node_modules/ws/node_modules/bufferutil/build
./node_modules/ws/node_modules/bufferutil/build/Release
./node_modules/ws/node_modules/bufferutil/src
(default) bmcqueen:blockstack-browser bmcqueen$
```

I've backed off HEAD and gone down to v0.14.0, and its the same error.

**Comment by bmcqueen** [comment]
trying again following the special osx install procedures
