### ISSUE TITLE
Cannot sign in to any app

### ISSUE THREAD

**Issue by n4cr** [blockstack/blockstack-browser#830]
When I try to login to any app, lets say Hello Blockstack app, I get a 500 error with the browser console log:
<img width="677" alt="screen shot 2017-09-27 at 00 22 42" src="https://user-images.githubusercontent.com/1065473/30888477-07388dee-a321-11e7-9d4c-97ca82418a8b.png">

On the server side here is the log:

```
[2017-09-27 01:11:55,733] [DEBUG] [config:877] (11533.140737012978624) Change blockstack-client.client_version to 0.14.2.0
[2017-09-27 01:11:55,738] [DEBUG] [config:895] (11533.140737012978624) Override blockstack-client.port from 6263 to 6264
[2017-09-27 01:11:55,746] [ERROR] [rpc:3439] (11533.140737012978624) 'None' is not valid under any of the given schemas

Failed validating 'anyOf' in schema['properties']['blockchain_id']:
    {'anyOf': [{'pattern': '^([a-z0-9\\-_.+]{3,37})$', 'type': 'string'},
               {'type': 'null'}]}

On instance['blockchain_id']:
    'None'
Traceback (most recent call last):
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 3436, in _dispatch
    'DELETE': {
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/rpc.py", line 512, in GET_auth
    except ValidationError as ve:
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/blockstack_client/app.py", line 86, in app_make_session

  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/tmp/blockstack-venv/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
ValidationError: 'None' is not valid under any of the given schemas

Failed validating 'anyOf' in schema['properties']['blockchain_id']:
    {'anyOf': [{'pattern': '^([a-z0-9\\-_.+]{3,37})$', 'type': 'string'},
               {'type': 'null'}]}

On instance['blockchain_id']:
    'None'
```

This is thrown on a freshly created account with localstorage cleared already (though before that I had deleted an account with a username and the username was created on an older version of blockstack. at the moment I cannot see the username even if I restore my old account).

**Comment by n4cr** [comment]
Found a solution to this. It seems blockstack server was not restarted when I installed the new version. So I think the BE was inconsistent with the FE and was causing the problem. Probably the fix for this bug is to make sure the server is restarted after an update is installed.

**Comment by jackzampolin** [comment]
Closing as this is solved.
